name: Deploy Production

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write   # required for Workload Identity Federation
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      - name: Upload static files to GCS (exclude GitHub files)
        env:
          BUCKET: ${{ secrets.GCS_BUCKET_NAME }}
        run: |
          set -euo pipefail
          DEST="gs://${BUCKET}"
          echo "Deploying files to $DEST"
          # Exclude .github folder and hidden files (like .git)
          gsutil -m rsync -r -d -x "^\..*|^.github/.*" ./ "$DEST"

      # Optional: Set caching rules for better performance
      - name: Set cache headers
        env:
          BUCKET: ${{ secrets.GCS_BUCKET }}
        run: |
          DEST="gs://${BUCKET}"
          echo "Setting cache headers..."
          # Cache static assets aggressively
          gsutil -m setmeta -h "Cache-Control:public,max-age=31536000,immutable" \
            $(gsutil ls "${DEST}/**" | grep -E '\.(css|js|png|jpg|jpeg|gif|svg|ico)$') || true
          # No-cache for HTML so updates are always fresh
          gsutil -m setmeta -h "Cache-Control:no-cache" \
            $(gsutil ls "${DEST}/**" | grep -E '\.html$') || true
